name: Auto Add Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to Akasa project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/oatrice/projects/9
          github-token: ${{ secrets.PROJECT_PAT }}
